### ISSUE TITLE
Service discovery HA

### ISSUE THREAD

**Issue by mascatul** [nistvan86/esphome-q7rf#3]
Hello i managed to compile and connect the radio beacon on an esp 8266 but i cannot see the pairing service in HA 
The switch seems ok i get the from the logs

[D][q7rf.switch:398]: Resending last state.
[D][q7rf.switch:305]: Sent message: HEAT OFF
[D][switch:021]: 'Q7RF switch' Toggling ON.
[D][switch:037]: 'Q7RF switch': Sending state ON
[D][q7rf.switch:381]: Handling prioritized message.
[D][q7rf.switch:305]: Sent message: HEAT ON

My esp looks like this :
```

esphome:
  name: rf-bridge

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "x"

ota:
  password: "x"

wifi:
  ssid: "IOT"
  password: "x"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Radio-Beacon Fallback Hotspot"
    password: "x"

captive_portal:
web_server:
  port: 80
  
external_components:
  - source: github://nistvan86/esphome-q7rf@main
    components: [ q7rf ]

switch:
  - platform: q7rf
    name: Q7RF switch
    cs_pin: D1
    q7rf_device_id: 0x6ed5
    q7rf_resend_interval: 60000
    q7rf_turn_on_watchdog_interval: 0

spi:
  clk_pin: D2
  miso_pin: D3
  mosi_pin: D4
```

So what am i missing? any help is welcome

Thanks in advance

UPDATE : Im stupid don't mind me thank you for your work
